package br.com.tjgwp.business.entity.user;

public enum UserHistoryType {

	NEW_BOOK, CHANGED_BOOK, NEW_CHAPTER, CHANGED_CHAPTER, CHANGED_BOOK_CAPE, CHANGED_CHAPTER_CAPE,
	NEW_FOLLOWER, NEW_FOLLOWING,
	CHANGED_PROFILE_PICTURE, CHANGED_CAPE_PICTURE,
	SIGNED_IN, SIGNED_OUT;
}
